Openeuropa 2101
openeuropa/triple-store-dev pull request #13
Opened 2019-07-31 15:05 UTC by sergepavle

2019-09-11 09:10 UTC, upchuk submitted a review, later dismissed

2019-09-24 07:40 UTC, ademarco requested changes
Not sure this should be done against the `master` branch, we should discuss this first.

2019-09-30 08:42 UTC, ademarco submitted a review, later dismissed

2019-09-30 08:42 UTC, ademarco commented on robo.yml
> +    format: "zip"
When building I get a 404:

![image](https://user-images.githubusercontent.com/153362/65862632-f3574000-e36e-11e9-83bf-02533fbf9d78.png)

And indeed that URL seems not to point to any resource.

2019-09-30 08:46 UTC, ademarco commented on robo.yml
> +    format: "zip"
The URL I found on the [DET page](https://publications.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/det) seems to be this one:

```
https://publications.europa.eu/euvoc-portlet/download?cellarURI=http%3A%2F%2Fpublications.europa.eu%2Fresource%2Fcellar%2F1deb8f26-d93d-11e9-9c4e-01aa75ed71a1.0001.02%2FDOC_1&fileName=skos-core.rdf
```

It also seems not to be a ZIP file.

2019-09-30 11:06 UTC, brummbar approved these changes

2019-09-30 11:07 UTC, ademarco approved these changes

2019-09-30 11:07 UTC, merged