EWPP-1109: Update SKOS vocabularies.
openeuropa/triple-store-dev pull request #49
Opened 2021-05-18 17:35 UTC by sergepavle

2021-05-20 12:35 UTC, nagyad approved these changes, later dismissed

2021-05-21 09:04 UTC, imanoleguskiza approved these changes, later dismissed

2021-05-21 12:26 UTC, brummbar requested changes
Blocked because DET version 1.5.0 doesn't mark non-EC bodies as  concept scheme.

1.4.0
```
<rdf:Description rdf:about="http://data.europa.eu/uxp/non-EC_bodies">
	<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>
	<prefLabel xmlns="http://www.w3.org/2004/02/skos/core#" xml:lang="en">Non-EC bodies</prefLabel>
</rdf:Description>
```

1.5.0
```
<rdf:Description rdf:about="http://data.europa.eu/uxp/non-EC_bodies">
	<prefLabel xmlns="http://www.w3.org/2004/02/skos/core#" xml:lang="en">Non-EC bodies</prefLabel>
</rdf:Description>
```

2021-05-31 12:18 UTC, nagyad approved these changes

2021-06-02 07:56 UTC, brummbar approved these changes

2021-06-02 07:57 UTC, merged