EWPP-1930: Update vocabularies.
openeuropa/triple-store-dev pull request #57
Opened 2022-01-26 15:52 UTC by nagyad

2022-01-27 12:41 UTC, sergepavle requested changes

2022-01-27 12:41 UTC, sergepavle commented on robo.yml
> +    url: "http://publications.europa.eu/resource/cellar/76166330-581c-11ec-91ac-01aa75ed71a1.0001.01/DOC_1"
Looks like should be:
```suggestion
    url: "http://publications.europa.eu/resource/cellar/76166330-581c-11ec-91ac-01aa75ed71a1.0001.03/DOC_1"
```
As I see previously we used DET-skos-core.rdf

2022-01-27 12:41 UTC, sergepavle commented on robo.yml
> +    url: "http://publications.europa.eu/resource/cellar/bcd714b1-5f05-11ec-9c6c-01aa75ed71a1.0001.03/DOC_1"
Here also should be used correct file (as before)
```suggestion
    url: "http://publications.europa.eu/resource/cellar/bcd714b1-5f05-11ec-9c6c-01aa75ed71a1.0001.04/DOC_1"
```
Currently, image event can be build with http://publications.europa.eu/resource/cellar/bcd714b1-5f05-11ec-9c6c-01aa75ed71a1.0001.03/DOC_1

2022-01-27 18:00 UTC, sergepavle submitted a review, later dismissed

2022-01-31 14:19 UTC, imanoleguskiza requested changes

2022-01-31 14:19 UTC, imanoleguskiza commented on robo.yml
> +    url: "http://publications.europa.eu/resource/cellar/9d7afcb9-8684-11eb-ac4c-01aa75ed71a1.0001.01/DOC_1"
According to https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/place&version=20211208-0, the latest skos-ap-act file is http://publications.europa.eu/resource/cellar/87ec948c-581c-11ec-91ac-01aa75ed71a1.0001.03/DOC_1

2022-01-31 15:04 UTC, imanoleguskiza approved these changes

2022-01-31 15:48 UTC, sergepavle approved these changes

2022-02-02 09:17 UTC, merged